import type { Metadata } from "next";
import "./globals.css";
import Header from "@/componets/Header";
import Provider from "@/Providers/Provider";
import Footer from "@/componets/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
         <div className=" min-h-[70vh]">
           {children}
         </div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
